# Generated by Django 3.2 on 2021-05-28 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=150, verbose_name='Номер этапа')),
                ('content', models.TextField(blank=True, verbose_name='Описание процедуры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Этап очистки',
                'verbose_name_plural': 'Этапы очистки',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('telephone_number', models.CharField(max_length=150, verbose_name='Номер телефона клиента')),
                ('activity', models.CharField(max_length=150, verbose_name='Род деятельности')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('number_of_visits', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=150, verbose_name='Наименование услуги')),
                ('content', models.TextField(blank=True, verbose_name='Описание услуги')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='продолжительность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления услуги')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d', verbose_name='Фото')),
                ('amount', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['-price'],
            },
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateTimeField(verbose_name='Дата визита')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('duration', models.DurationField(default='03:00:00', help_text='часы:минуты:секунды', verbose_name='Длительность процедуры')),
                ('content', models.TextField(blank=True, verbose_name='Описание процедуры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('photo_before', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d', verbose_name='Фото до')),
                ('photo_after', models.ImageField(upload_to='photo/%Y/%m/%d', verbose_name='Фото после')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.clients', verbose_name='Клиент')),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.services', verbose_name='Наименование услуги')),
            ],
            options={
                'verbose_name': 'Визит',
                'verbose_name_plural': 'Визиты',
                'ordering': [],
            },
        ),
    ]
