# Generated by Django 3.2 on 2021-05-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=150, verbose_name='Наименование услуги')),
                ('content', models.TextField(blank=True, verbose_name='Описание услуги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления услуги')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Этап очистки',
                'verbose_name_plural': 'Этапы очистки',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=150, verbose_name='Наименование услуги')),
                ('content', models.TextField(blank=True, verbose_name='Описание услуги')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='продолжительность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления услуги')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': [],
            },
        ),
    ]
