# Generated by Django 3.2 on 2021-05-30 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='activity',
            field=models.CharField(blank=True, max_length=150, verbose_name='Род деятельности'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='birthday',
            field=models.DateField(blank=True, default='10.12.2000', verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='services',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='visits',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='services.clients', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='duration',
            field=models.DurationField(blank=True, default='03:00:00', help_text='часы:минуты:секунды', verbose_name='Длительность процедуры'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='photo_after',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d', verbose_name='Фото после'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='price',
            field=models.IntegerField(blank=True, default='250', verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='service_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='services.services', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='work_date',
            field=models.DateTimeField(blank=True, verbose_name='Дата визита'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('content', models.TextField(blank=True, verbose_name='Содерджание комментария')),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.visits', verbose_name='Комментарий')),
            ],
        ),
    ]
